### ISSUE TITLE
Eliminazione automatica del pannello quando viene eliminato il canale | Comando per rimuovere un pannello

### ISSUE THREAD

**Issue by Bananonz** [ITKewai/Ciro-Discord-Bot#2]
Quando un canale, dove è presente il ticket, viene eliminato, il pannello viene eliminato a sua stessa volta.
Aggiunta del comando per rimuovere un pannello.

**Comment by ITKewai** [comment]
feature rifiutata, per motivi di ripristino, è stato aggiunto invece che se il canale  ticket viene eliminato viene mandato il messaggio che è stato chiuso il ticket
