### ISSUE TITLE
comando clone

### ISSUE THREAD

**Issue by Katakuri0** [ITKewai/Ciro-Discord-Bot#4]
quando cloni un canale non copia il 'mostra i membri del ruolo in una categoria separata dagli utenti online' e 'permetti a chiunque di @mezionare questo ruolo'

**Comment by ITKewai** [comment]
Fixato con l'update [378eb97](https://github.com/ITKewai/Ciro-Discord-Bot/commit/378eb979d021d9af9d3dbcac41c42c674234ff0e)
